// ============================================================
//  Azure Container Registry — Template réutilisable
//  Exercice : configuration d'un registre de conteneurs ACR
//  Usage : az deployment group create \
//            --resource-group <rg> \
//            --template-file main.bicep \
//            --parameters @params.bicepparam
// ============================================================

// ── Paramètres ──────────────────────────────────────────────

@description('Nom du registre ACR — unique globalement, minuscules, 5-50 caractères')
@minLength(5)
@maxLength(50)
param registryName string

@description('Région Azure')
@allowed([
  'canadaeast'
  'canadacentral'
  'eastus'
  'eastus2'
  'northcentralus'
  'westus2'
  'westeurope'
  'northeurope'
])
param location string = 'canadacentral'

@description('SKU du registre')
@allowed(['Basic', 'Standard', 'Premium'])
param sku string = 'Basic'

@description('Activer le compte administrateur (non recommandé en prod — préférer les identités managées)')
param adminUserEnabled bool = false

@description('Activer le pull anonyme (lecture publique sans authentification)')
param anonymousPullEnabled bool = false

@description('Autoriser l\'accès réseau public')
@allowed(['Enabled', 'Disabled'])
param publicNetworkAccess string = 'Enabled'

@description('Activer la politique de rétention des images non-taguées')
param enableRetentionPolicy bool = false

@description('Durée de rétention des images non-taguées en jours (nécessite SKU Premium)')
@minValue(1)
@maxValue(365)
param retentionPolicyDays int = 7

@description('Activer la politique de soft delete')
param enableSoftDelete bool = false

@description('Durée de rétention soft delete en jours')
@minValue(1)
@maxValue(90)
param softDeleteRetentionDays int = 7

@description('Activer la redondance de zone (nécessite SKU Premium et région compatible)')
param zoneRedundancy bool = false

@description('Activer le data endpoint dédié (nécessite SKU Premium)')
param dataEndpointEnabled bool = false

@description('Tags à appliquer à toutes les ressources')
param tags object = {
  environment: 'dev'
  managedBy: 'bicep'
}

// ── Validation SKU / fonctionnalités Premium ─────────────────
// Note : retentionPolicy, zoneRedundancy et dataEndpoint
// nécessitent le SKU Premium. Le déploiement échouera si ces
// options sont activées avec Basic ou Standard.

// ── Registre ACR ─────────────────────────────────────────────

resource registry 'Microsoft.ContainerRegistry/registries@2026-01-01-preview' = {
  name: registryName
  location: location
  tags: tags
  sku: {
    name: sku
    tier: sku
  }
  properties: {
    adminUserEnabled: adminUserEnabled
    policies: {
      quarantinePolicy: {
        status: 'disabled'
      }
      trustPolicy: {
        type: 'Notary'
        status: 'disabled'
      }
      retentionPolicy: {
        days: retentionPolicyDays
        status: enableRetentionPolicy ? 'enabled' : 'disabled'
      }
      exportPolicy: {
        status: 'enabled'
      }
      azureADAuthenticationAsArmPolicy: {
        status: 'enabled'
      }
      softDeletePolicy: {
        retentionDays: softDeleteRetentionDays
        status: enableSoftDelete ? 'enabled' : 'disabled'
      }
    }
    encryption: {
      status: 'disabled'
    }
    dataEndpointEnabled: dataEndpointEnabled
    regionalEndpoints: 'Disabled'
    endpointProtocol: 'IPv4'
    publicNetworkAccess: publicNetworkAccess
    networkRuleBypassOptions: 'AzureServices'
    networkRuleBypassAllowedForTasks: false
    zoneRedundancy: zoneRedundancy ? 'Enabled' : 'Disabled'
    anonymousPullEnabled: anonymousPullEnabled
    metadataSearch: 'Disabled'
    roleAssignmentMode: 'LegacyRegistryPermissions'
    autoGeneratedDomainNameLabelScope: 'Unsecure'
  }
}

// ── Scope Maps (permissions granulaires) ─────────────────────

resource scopeAdmin 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registry
  name: '_repositories_admin'
  properties: {
    description: 'Lecture, écriture et suppression sur tous les dépôts'
    actions: [
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
      'repositories/*/content/read'
      'repositories/*/content/write'
      'repositories/*/content/delete'
    ]
  }
}

resource scopePull 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registry
  name: '_repositories_pull'
  properties: {
    description: 'Pull uniquement sur tous les dépôts'
    actions: [
      'repositories/*/content/read'
    ]
  }
}

resource scopePullMetadataRead 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registry
  name: '_repositories_pull_metadata_read'
  properties: {
    description: 'Pull et lecture des métadonnées sur tous les dépôts'
    actions: [
      'repositories/*/content/read'
      'repositories/*/metadata/read'
    ]
  }
}

resource scopePush 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registry
  name: '_repositories_push'
  properties: {
    description: 'Push et pull sur tous les dépôts'
    actions: [
      'repositories/*/content/read'
      'repositories/*/content/write'
    ]
  }
}

resource scopePushMetadataWrite 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registry
  name: '_repositories_push_metadata_write'
  properties: {
    description: 'Push, pull et écriture des métadonnées sur tous les dépôts'
    actions: [
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
      'repositories/*/content/read'
      'repositories/*/content/write'
    ]
  }
}

// ── Outputs ──────────────────────────────────────────────────

output registryName     string = registry.name
output loginServer      string = registry.properties.loginServer
output registryId       string = registry.id
output registryLocation string = registry.location
